### ISSUE TITLE
Handle Tables Owned by Different Users

### ISSUE THREAD

**Issue by rgs258** [FlipperPA/django-pg-copy#10]
Presently, the `DROP OWNED BY {settings.DATABASES[database]["USER"]};` command at https://github.com/FlipperPA/django-pg-copy/blob/main/pg_copy/management/commands/pg_restore.py#L167 will fail when the current role doesn't match the `settings.DATABASES[database]["USER"]`. The failure looks something like: 
```
ERROR:  permission denied to drop objects
```

https://github.com/FlipperPA/django-pg-copy/pull/9 aims to work around this and avoid the above error, but will not address that some tables (or other objects) might be owned by a different role than `settings.DATABASES[database]["USER"]`. As such, tables (and/or other objects) may remain in the database given for `-d {db}` who's ownership is different.

A solution might be to check for Django's [assume_role](https://docs.djangoproject.com/en/5.0/ref/databases/#role) option, and use that for the `SET ROLE` and `DROP OWNED BY` commands. We might then also add a new `pg_drop` command because projects using multiple roles will likely already need to configure multiple "DATABASES" for the purpose of interacting on behalf of each role.

**Comment by rgs258** [comment]
Another solution could be to just offer a `--no-drop` option which would be a way to offload responsibility for dropping objects to some external process (or for dropping to be skipped altogether). 

It might be best to do both add the `--no-drop` option AND add the `pg_drop` command, thus giving users the opportunity to choose the best path for them.

**Comment by FlipperPA** [comment]
I've added `--no-drop` for starters. If you're interested in doing more, please feel free, but I figured this was a good start!
