### ISSUE TITLE
Does this work on docker deployments?

### ISSUE THREAD

**Issue by keithlowc** [FlipperPA/django-pg-copy#5]
Usually when developing on docker we have two containers one is the webserver and the other one is the psql database. I tried running it directly on the webserver as stated on the tutorial but got the following error when running the following command

`python manage.py pg_backup`

```
/bin/sh: 1: pg_dump: not found
```

I am pretty certain it has to do with the fact that we are missing the psql client on the webserver container. However, how would we go about this as the two are in separate containers. 

Let me know, if there are any ideas! 

Thanks,

**Comment by FlipperPA** [comment]
Hi @keithlowc - you're absolutely right, this package wraps `pg_dump` / `pg_restore`, so you'd need to install the client as part of your container:

`sudo apt-get install postgresql-client`

Good luck!
