### ISSUE TITLE
django-pg-copy comping up with pg_dump error

### ISSUE THREAD

**Issue by vandana1408** [FlipperPA/django-pg-copy#8]
I'm having an issue when I try to run `python manage.py pg_backup`. I'm running the command from a web container in my django project which is separate from the database container and I get this message: 

```
Backing up database 'dev_db' on host 'db' to file 'db_backup/2023-09-11-01-27-23.sqlc'...
pg_dump --format=custom --file=db_backup/2023-09-11-01-27-23.sqlc -c -O -x -h db -p 5432 -U postgres   dev_db
/bin/sh: pg_dump: not found
Command 'pg_dump --format=custom --file=db_backup/2023-09-11-01-27-23.sqlc -c -O -x -h db -p 5432 -U postgres   dev_db' returned non-zero exit status 127.
```

just wondering if there's anything that might need to be added to the web container's set up in the Dockerfile or docker-compose.yml file.

**Comment by FlipperPA** [comment]
The pg_dump command is not in the path of your container. Are you sure it is installed? What Linux distribution are you running in the container?

**Comment by vandana1408** [comment]
I'm using WSL2 to run the docker container but I have a web container and db container in the platform.

**Comment by vandana1408** [comment]
Managed to get pg_backup to work but the other developer I'm working with is struggling to get pg_restore to work on his computer. The tables are all there but none of the data is. We were just wondering if this package is aimed at restoring the schema or restores the data as well?

**Comment by vandana1408** [comment]
The file I've done a pg_backup to is approx. 140KB.

**Comment by FlipperPA** [comment]
@vandana1408 Are you still getting this error?

```
pg_dump: error: server version: 13.1; pg_dump version: 12.10
pg_dump: error: aborting because of server version mismatch
```

I'm guessing you may have gotten past it, but wanted to check.
